version: '3.8'
include:
  - "proxy.yaml"
services:

  web:
    image: oefrager_docker
    restart: always
    networks:
        backend: {}
    ports:
    - "172.20.0.5"
    env_file:
    - .env
    #volumes:

  db:
    image: mysql:8
    restart: always
    networks:
        backend: {}
    ports:
    - "172.20.0.10"
    env_file:
    - .env
    #volumes:
    

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
